
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wswpqesjkofptwkyevag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzd3BxZXNqa29mcHR3a3lldmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTI3ODYsImV4cCI6MjA3MDA4ODc4Nn0.vlbZ2Oux4bChCwCtHqWqY5OuMajpAuPbYGPwZ8zAUbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
