// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oesqovainsntvqpwqirm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lc3FvdmFpbnNudHZxcHdxaXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyOTkzMDIsImV4cCI6MjA1Njg3NTMwMn0.ZIuKMWmKhLfvcOljnILmaOq63tVpBvetRciBRIIHBl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);